SPDX-License-Identifier: CC-BY-SA-4.0
copyrights:
- Copyright (C) 1988, 1998 On-Line Applications Research Corporation (OAR)
enabled-by: true
glossary-type: term
links:
- role: glossary-member
  uid: ../glossary-general
term: stack
text: |
  A data structure that is managed using a Last In First Out (LIFO)
  discipline.  Each task has a stack associated with it which is used to
  store return information and local variables.
type: glossary
