build:
  arch: sparc
  bsp: leon3
  config-ini: |
    [${arch}/${bsp}]
    RTEMS_SMP = True
    RTEMS_QUAL = True
    RTEMS_QUAL_ONLY = True
    BUILD_TESTS = False
    BUILD_VALIDATIONTESTS = True
    INSTALL_LEGACY_MAKEFILES = False
  doxyfile-template: templates/Doxyfile
  enabled:
  - RTEMS_QUAL
  - RTEMS_SMP
  source-directory: external/rtems
  sources:
  - bsps/shared/cache/cacheimpl.h
  - bsps/shared/dev/clock/clockimpl.h
  - cpukit/doxygen.h
  - cpukit/libcsupport/src/malloc_p.h
  - cpukit/libtest/t-test-rtems.h
  - cpukit/score/cpu/sparc/syscall.h
  - cpukit/score/src/opt_compat.h
  - cpukit/score/src/opt_ffclock.h
  - cpukit/score/src/opt_ntp.h
  - gccdeps.py
  - long_gcc.py
  - testsuites/doxygen.h
  - waf
  - wscript
  uids:
  - /build/cpukit/librtemscpu
  - /build/cpukit/librtemstest
  - /build/testsuites/validation/grp
  workspace-directory: workspace/rtems
spec:
  cache-directory: cache
  spec-type-root-uid: /spec/root
  paths:
  - spec
  - external/rtems/spec
glossary:
  project-groups:
  - /glossary-general
  project-target: external/rtems-docs/c-user/glossary.rst
  documents:
  - rest-source-paths:
    - external/rtems-docs/eng
    target: external/rtems-docs/eng/glossary.rst
appl-config:
  doxygen-target: external/rtems/cpukit/doxygen/appl-config.h
  groups:
  - uid: /if/acfg/group-bdbuf
    target: external/rtems-docs/c-user/config/bdbuf.rst
  - uid: /if/acfg/group-bsp
    target: external/rtems-docs/c-user/config/bsp-related.rst
  - uid: /if/acfg/group-classic
    target: external/rtems-docs/c-user/config/classic-api.rst
  - uid: /if/acfg/group-classicinit
    target: external/rtems-docs/c-user/config/classic-init-task.rst
  - uid: /if/acfg/group-devdrv
    target: external/rtems-docs/c-user/config/device-driver.rst
  - uid: /if/acfg/group-eventrecord
    target: external/rtems-docs/c-user/config/event-record.rst
  - uid: /if/acfg/group-filesystem
    target: external/rtems-docs/c-user/config/filesystem.rst
  - uid: /if/acfg/group-general
    target: external/rtems-docs/c-user/config/general.rst
  - uid: /if/acfg/group-idle
    target: external/rtems-docs/c-user/config/idle-task.rst
  - uid: /if/acfg/group-mpci
    target: external/rtems-docs/c-user/config/mpci.rst
  - uid: /if/acfg/group-posix
    target: external/rtems-docs/c-user/config/posix-api.rst
  - uid: /if/acfg/group-posixinit
    target: external/rtems-docs/c-user/config/posix-init-thread.rst
  - uid: /if/acfg/group-schedgeneral
    target: external/rtems-docs/c-user/config/scheduler-general.rst
  - uid: /if/acfg/group-stackalloc
    target: external/rtems-docs/c-user/config/task-stack-alloc.rst
validation:
  base-directory: external/rtems
interface:
  item-level-interfaces:
  - /if/build-options/container
  - /if/compiler/container
  - /if/use/container
  domains:
    /if/domains/api: external/rtems
interface-documentation:
- directives-target: external/rtems-docs/c-user/sem/directives.rst
  group: /groups/api/classic/sem
  introduction-target: external/rtems-docs/c-user/sem/introduction.rst
spec-verification:
  root-type: /spec/root
spec-documentation:
  root-type: /spec/root
  doc-target: external/rtems-docs/eng/req/items.rst
