build:
  arch: sparc
  bsp: gr712rc
  config-ini: |
    [${arch}/${bsp}]
    RTEMS_SMP = True
    RTEMS_QUAL = True
    RTEMS_QUAL_ONLY = True
    BUILD_TESTS = False
    BUILD_MEMBENCH = True
    BUILD_VALIDATIONTESTS = True
    BSP_PRINT_EXCEPTION_CONTEXT = False
  doxyfile-template: templates/Doxyfile
  enabled:
  - bsps/sparc/leon3
  - INSTALL_LEGACY_MAKEFILES
  - RTEMS_QUAL
  - RTEMS_QUAL_ONLY
  - RTEMS_SMP
  source-directory: modules/rtems
  sources:
  - bsps/shared/doxygen.h
  - bsps/shared/cache/cacheimpl.h
  - bsps/shared/dev/clock/clockimpl.h
  - bsps/sparc/shared/doxygen.h
  - cpukit/doxygen.h
  - cpukit/doxygen/appl-config.h
  - cpukit/doxygen/top-level-groups.h
  - cpukit/libc/string/local.h
  - cpukit/libcsupport/src/malloc_p.h
  - cpukit/libtest/t-test-rtems.h
  - cpukit/score/cpu/sparc/syscall.h
  - cpukit/score/src/opt_compat.h
  - cpukit/score/src/opt_ffclock.h
  - cpukit/score/src/opt_ntp.h
  - gccdeps.py
  - long_gcc.py
  - testsuites/validation/tc-basedefs-pendant.h
  - testsuites/validation/tc-userext.h
  - testsuites/validation/tr-model-chains-api.h
  - testsuites/validation/tr-model-events-mgr.h
  - testsuites/validation/ts-config.h
  - testsuites/validation/ts-default.h
  - testsuites/validation/ts-fatal-sysinit.h
  - testsuites/validation/ts-idle.h
  - testsuites/validation/tx-support.h
  - testsuites/validation/tx-thread-queue.h
  - waf
  - wscript
  uids:
  - /build/cpukit/librtemscpu
  - /build/cpukit/librtemstest
  - /build/testsuites/membench/grp
  - /build/testsuites/validation/grp
  workspace-directory: workspace/rtems
spec:
  cache-directory: cache
  spec-type-root-uid: /spec/root
  paths:
  - spec-spec
  - spec
  - spec-glossary
  - modules/rtems/spec
glossary:
  project-groups:
  - /glossary-general
  project-header: Glossary
  project-target: modules/rtems-docs/c-user/glossary.rst
  documents:
  - header: Glossary
    rest-source-paths:
    - modules/rtems-docs/eng
    target: modules/rtems-docs/eng/glossary.rst
appl-config:
  doxygen-target: modules/rtems/cpukit/doxygen/appl-config.h
  groups:
  - uid: /acfg/if/group-bdbuf
    target: modules/rtems-docs/c-user/config/bdbuf.rst
  - uid: /acfg/if/group-bsp
    target: modules/rtems-docs/c-user/config/bsp-related.rst
  - uid: /acfg/if/group-classic
    target: modules/rtems-docs/c-user/config/classic-api.rst
  - uid: /acfg/if/group-classicinit
    target: modules/rtems-docs/c-user/config/classic-init-task.rst
  - uid: /acfg/if/group-devdrv
    target: modules/rtems-docs/c-user/config/device-driver.rst
  - uid: /acfg/if/group-eventrecord
    target: modules/rtems-docs/c-user/config/event-record.rst
  - uid: /acfg/if/group-filesystem
    target: modules/rtems-docs/c-user/config/filesystem.rst
  - uid: /acfg/if/group-general
    target: modules/rtems-docs/c-user/config/general.rst
  - uid: /acfg/if/group-idle
    target: modules/rtems-docs/c-user/config/idle-task.rst
  - uid: /acfg/if/group-mpci
    target: modules/rtems-docs/c-user/config/mpci.rst
  - uid: /acfg/if/group-posix
    target: modules/rtems-docs/c-user/config/posix-api.rst
  - uid: /acfg/if/group-posixinit
    target: modules/rtems-docs/c-user/config/posix-init-thread.rst
  - uid: /acfg/if/group-schedgeneral
    target: modules/rtems-docs/c-user/config/scheduler-general.rst
  - uid: /acfg/if/group-stackalloc
    target: modules/rtems-docs/c-user/config/task-stack-alloc.rst
validation:
  base-directory: modules/rtems
interface:
  item-level-interfaces:
  - /build-options/if/container
  - /compiler/if/container
  - /user/if/container
  domains:
    /if/domain: modules/rtems
    /dev/if/domain: modules/rtems
interface-documentation:
- directives-target: modules/rtems-docs/c-user/barrier/directives.rst
  group: /rtems/barrier/if/group
  introduction-target: modules/rtems-docs/c-user/barrier/introduction.rst
- directives-target: modules/rtems-docs/c-user/cache/directives.rst
  group: /rtems/cache/if/group
  introduction-target: modules/rtems-docs/c-user/cache/introduction.rst
- directives-target: modules/rtems-docs/c-user/dual-ported-memory/directives.rst
  group: /rtems/dpmem/if/group
  introduction-target: modules/rtems-docs/c-user/dual-ported-memory/introduction.rst
- directives-target: modules/rtems-docs/c-user/fatal-error/directives.rst
  group: /rtems/fatal/if/group
  introduction-target: modules/rtems-docs/c-user/fatal-error/introduction.rst
- directives-target: modules/rtems-docs/c-user/timer/directives.rst
  group: /rtems/timer/if/group
  introduction-target: modules/rtems-docs/c-user/timer/introduction.rst
- directives-target: modules/rtems-docs/c-user/initialization/directives.rst
  group: /rtems/init/if/group
  introduction-target: modules/rtems-docs/c-user/initialization/introduction.rst
- directives-target: modules/rtems-docs/c-user/io/directives.rst
  group: /rtems/io/if/group
  introduction-target: modules/rtems-docs/c-user/io/introduction.rst
- directives-target: modules/rtems-docs/c-user/kernel-character-io/directives.rst
  group: /rtems/io/if/group-3
  introduction-target: modules/rtems-docs/c-user/kernel-character-io/introduction.rst
- directives-target: modules/rtems-docs/c-user/region/directives.rst
  group: /rtems/region/if/group
  introduction-target: modules/rtems-docs/c-user/region/introduction.rst
- directives-target: modules/rtems-docs/c-user/multiprocessing/directives.rst
  group: /rtems/mp/if/group
  introduction-target: modules/rtems-docs/c-user/multiprocessing/introduction.rst
- directives-target: modules/rtems-docs/c-user/semaphore/directives.rst
  group: /rtems/sem/if/group
  introduction-target: modules/rtems-docs/c-user/semaphore/introduction.rst
- directives-target: modules/rtems-docs/c-user/event/directives.rst
  group: /rtems/event/if/group
  introduction-target: modules/rtems-docs/c-user/event/introduction.rst
- directives-target: modules/rtems-docs/c-user/partition/directives.rst
  group: /rtems/part/if/group
  introduction-target: modules/rtems-docs/c-user/partition/introduction.rst
- directives-target: modules/rtems-docs/c-user/task/directives.rst
  group: /rtems/task/if/group
  introduction-target: modules/rtems-docs/c-user/task/introduction.rst
- directives-target: modules/rtems-docs/c-user/message/directives.rst
  group: /rtems/message/if/group
  introduction-target: modules/rtems-docs/c-user/message/introduction.rst
- directives-target: modules/rtems-docs/c-user/object-services/directives.rst
  group: /rtems/object/if/group
  introduction-target: modules/rtems-docs/c-user/object-services/introduction.rst
- directives-target: modules/rtems-docs/c-user/signal/directives.rst
  group: /rtems/signal/if/group
  introduction-target: modules/rtems-docs/c-user/signal/introduction.rst
- directives-target: modules/rtems-docs/c-user/user-extensions/directives.rst
  group: /rtems/userext/if/group
  introduction-target: modules/rtems-docs/c-user/user-extensions/introduction.rst
- directives-target: modules/rtems-docs/c-user/scheduling-concepts/directives.rst
  group: /rtems/scheduler/if/group
  introduction-target: modules/rtems-docs/c-user/scheduling-concepts/introduction.rst
- directives-target: modules/rtems-docs/c-user/clock/directives.rst
  group: /rtems/clock/if/group
  introduction-target: modules/rtems-docs/c-user/clock/introduction.rst
- directives-target: modules/rtems-docs/c-user/interrupt/directives.rst
  group: /rtems/intr/if/group
  introduction-target: modules/rtems-docs/c-user/interrupt/introduction.rst
- directives-target: modules/rtems-docs/c-user/rate-monotonic/directives.rst
  group: /rtems/ratemon/if/group
  introduction-target: modules/rtems-docs/c-user/rate-monotonic/introduction.rst
spec-verification:
  root-type: /spec/root
spec-documentation:
  doc-target: modules/rtems-docs/eng/req/items.rst
  hierarchy-subsection-name: Specification Item Hierarchy
  hierarchy-text: |
    The specification item types have the following hierarchy:
  ignore: '^$'
  item-types-subsection-name: Specification Item Types
  label-prefix: SpecType
  root-type: /spec/root
  section-label-prefix: ReqEng
  section-name: Specification Items
  value-types-subsection-name: Specification Attribute Sets and Value Types
