build:
  arch: sparc
  bsp: leon3
  config-ini: |
    [${arch}/${bsp}]
    RTEMS_SMP = True
    RTEMS_QUAL = True
    RTEMS_QUAL_ONLY = True
    BUILD_TESTS = False
    BUILD_VALIDATIONTESTS = True
  enabled:
  - RTEMS_QUAL
  - RTEMS_SMP
  source-directory: external/rtems
  sources:
  - bsps/shared/cache/cacheimpl.h
  - bsps/shared/dev/clock/clockimpl.h
  - cpukit/libcsupport/src/malloc_p.h
  - cpukit/libtest/t-test-rtems.h
  - cpukit/score/cpu/sparc/syscall.h
  - cpukit/score/src/opt_compat.h
  - cpukit/score/src/opt_ffclock.h
  - cpukit/score/src/opt_ntp.h
  - gccdeps.py
  - long_gcc.py
  - waf
  - wscript
  uids:
  - RTEMS-BUILD-CPUKIT-LIBRTEMSCPU
  - RTEMS-BUILD-CPUKIT-LIBRTEMSTEST
  - RTEMS-BUILD-TEST-VAL-GRP
  workspace-directory: workspace/rtems
spec:
  cache-directory: cache
  paths:
  - spec
  - external/rtems/spec
glossary:
  project-groups:
  - RTEMS-GLOS-GENERAL
  project-target: external/rtems-docs/c-user/glossary.rst
  documents:
  - rest-source-paths:
    - external/rtems-docs/eng
    target: external/rtems-docs/eng/glossary.rst
appl-config:
  groups:
  - uid: RTEMS-ACFG-BDBUF
    target: external/rtems-docs/c-user/config/bdbuf.rst
  - uid: RTEMS-ACFG-BSP
    target: external/rtems-docs/c-user/config/bsp-related.rst
  - uid: RTEMS-ACFG-CLASSIC
    target: external/rtems-docs/c-user/config/classic-api.rst
  - uid: RTEMS-ACFG-CLASSICINIT
    target: external/rtems-docs/c-user/config/classic-init-task.rst
  - uid: RTEMS-ACFG-DEVDRV
    target: external/rtems-docs/c-user/config/device-driver.rst
  - uid: RTEMS-ACFG-EVENTRECORD
    target: external/rtems-docs/c-user/config/event-record.rst
  - uid: RTEMS-ACFG-FILESYSTEM
    target: external/rtems-docs/c-user/config/filesystem.rst
  - uid: RTEMS-ACFG-GENERAL
    target: external/rtems-docs/c-user/config/general.rst
  - uid: RTEMS-ACFG-IDLE
    target: external/rtems-docs/c-user/config/idle-task.rst
  - uid: RTEMS-ACFG-MPCI
    target: external/rtems-docs/c-user/config/mpci.rst
  - uid: RTEMS-ACFG-POSIX
    target: external/rtems-docs/c-user/config/posix-api.rst
  - uid: RTEMS-ACFG-POSIXINIT
    target: external/rtems-docs/c-user/config/posix-init-thread.rst
  - uid: RTEMS-ACFG-SCHEDGENERAL
    target: external/rtems-docs/c-user/config/scheduler-general.rst
  - uid: RTEMS-ACFG-STACKALLOC
    target: external/rtems-docs/c-user/config/task-stack-alloc.rst
