SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
brief: |
  Builds a task according to the task configuration.
copyrights:
- Copyright (C) 2020 embedded brains GmbH (http://www.embedded-brains.de)
definition:
  default:
    body: null
    params:
    - const ${config:/name} *${.:/params[0]/name}
    - ${../types/id:/name} *${.:/params[1]/name}
    return: ${../status/code:/name}
  variants: []
description: null
enabled-by: true
interface-type: function
links:
- role: interface-placement
  uid: header
- role: interface-ingroup
  uid: group
name: rtems_task_build
notes: null
params:
- description: is the task configuration.
  dir: null
  name: config
- description: |
    is the pointer to an object identifier variable.  The identifier of the new
    task object will be stored in this variable, in case of a successful
    operation.
  dir: out
  name: id
return:
  return: null
  return-values:
  - description: |
      The requested operation was successful.
    value: ${../status/successful:/name}
  - description: |
      The ${.:/params[1]/name} parameter was ${/if/c/null:/name}.
    value: ${../status/invalid-address:/name}
  - description: |
      The task name was invalid.
    value: ${../status/invalid-name:/name}
  - description: |
      The initial task priority was invalid.
    value: ${../status/invalid-priority:/name}
  - description: |
      The multiprocessing support was not configured.
    value: ${../status/mp-not-configured:/name}
  - description: |
      There was no inactive task object available to build a new task.
    value: ${../status/too-many:/name}
  - description: |
      In multiprocessing configurations, there was no inactive global object
      available to build a new task.
    value: ${../status/too-many:/name}
  - description: |
      The provided task storage area was too small.  The task storage area
      includes the task stack, the thread-local storage, and the floating point
      context.
    value: ${../status/unsatisfied:/name}
  - description: |
      One of the task create extensions failed to create the new task.
    value: ${../status/unsatisfied:/name}
  - description: |
      In SMP configurations, the non-preemption mode was not supported.
    value: ${../status/unsatisfied:/name}
  - description: |
      In SMP configurations, the interrupt level mode was not supported.
    value: ${../status/unsatisfied:/name}
type: interface
