SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
brief: API
copyrights:
- Copyright (C) 2020 embedded brains GmbH (http://www.embedded-brains.de)
description: |
  This group contains the Task Manager API.
enabled-by: true
identifier: RTEMSAPIClassicTasks
interface-type: group
links:
- role: interface-placement
  uid: header
- role: interface-ingroup
  uid: ../group
name: Task Manager
type: interface
