SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
appl-config-option-type: feature-enable
copyrights:
- Copyright (C) 1988, 2008 On-Line Applications Research Corporation (OAR)
description: |
  In case this configuration option is defined, then the following BSP related
  configuration options are undefined:

  * ${bsp-idle-task-body:/name}

  * ${bsp-idle-task-stack-size:/name}

  * ${bsp-initial-extension:/name}

  * ${bsp-interrupt-stack-size:/name}

  * ${bsp-prerequisite-drivers:/name}

  * ${malloc-bsp-supports-sbrk:/name}
enabled-by: true
index-entries: []
interface-type: appl-config-option
links:
- role: requirement-refinement
  uid: ../req/disable-bsp-settings
- role: appl-config-group-member
  uid: group-bsp
name: CONFIGURE_DISABLE_BSP_SETTINGS
notes: null
type: interface
