SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
brief: |
  This constant can be used to indicate that the task should be created with
  the configured minimum stack size.
copyrights:
- Copyright (C) 2020, 2021 embedded brains GmbH & Co. KG
- Copyright (C) 1988, 2008 On-Line Applications Research Corporation (OAR)
definition:
  default: '0'
  variants: []
description: |
  Using this constant when specifying the task stack size indicates that this
  task is to be created with a stack size of the minimum stack size that was
  configured by the application. If not explicitly configured by the
  application, the default configured minimum stack size is
  ${minimum-stack-size:/name} which depends on the
  ${/glossary/target-arch:/term}. Since this uses the configured minimum stack
  size value, you may get a stack size that is smaller or larger than the
  recommended minimum. This can be used to provide large stacks for all tasks
  on complex applications or small stacks on applications that are trying to
  conserve memory.
enabled-by: true
index-entries: []
interface-type: define
links:
- role: interface-placement
  uid: header
- role: interface-ingroup
  uid: group
name: RTEMS_CONFIGURED_MINIMUM_STACK_SIZE
notes: null
type: interface
