SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
copyrights:
- Copyright (C) 2020 embedded brains GmbH (http://www.embedded-brains.de)
enabled-by: true
links:
- role: spec-member
  uid: root
- role: spec-refinement
  spec-key: appl-config-option-type
  spec-value: feature-enable
  uid: appl-config-option
spec-description: null
spec-example: null
spec-info:
  dict:
    attributes: {}
    description: |
      This set of attributes specifies an application configuration feature
      enable option.
    required-attributes: all
spec-name: Application Configuration Feature Enable Option Item Type
spec-type: appl-config-option-feature-enable
type: spec
