SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
copyrights:
- Copyright (C) 2020 embedded brains GmbH (http://www.embedded-brains.de)
enabled-by: true
links:
- role: spec-member
  uid: root
- role: spec-refinement
  spec-key: interface-type
  spec-value: appl-config-option
  uid: interface
spec-description: null
spec-example: null
spec-info:
  dict:
    attributes:
      appl-config-option-type:
        description: |
          It shall be the application configuration option type.
        spec-type: name
      description:
        description: |
          It shall be the description of the application configuration option.
          The description should be short and concentrate on the average case.
          All special cases, usage notes, constraints, error conditions,
          configuration dependencies, references, etc. should be described in
          the notes.  The ${appl-config-option-value:/spec-name} items have an
          attribute for constraints.
        spec-type: str
      index-entries:
        description: |
          It shall be a list of additional application configuration option
          document index entries.  The application configuration option name is
          automatically added to the document index.
        spec-type: list-str
      name:
        description: null
        spec-type: appl-config-option-name
      notes:
        description: |
          It shall be the notes to the application configuration option.
        spec-type: optional-str
      text:
        description: |
          It shall state the requirement for the application configuration
          option.
        spec-type: requirement-text
    description: |
      This set of attributes specifies an application configuration option.
    required-attributes: all
spec-name: Application Configuration Option Item Type
spec-type: appl-config-option
type: spec
