SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
copyrights:
- Copyright (C) 2020 embedded brains GmbH (http://www.embedded-brains.de)
enabled-by: true
links:
- role: spec-member
  uid: root
spec-description: null
spec-example: null
spec-info:
  str:
    assert:
    - re: ^(CONFIGURE_|BSP_)[A-Z0-9_]+$
    description: |
      This attribute value defines an application configuration option name.
spec-name: Application Configuration Option Name
spec-type: appl-config-option-name
type: spec
