SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
copyrights:
- Copyright (C) 2020 embedded brains GmbH (http://www.embedded-brains.de)
enabled-by: true
links:
- role: spec-member
  uid: root
spec-description: null
spec-example: null
spec-info:
  dict:
    attributes:
      max:
        description: |
          It shall be the maximum value of the application configuration
          option.
        spec-type: int-or-str
      min:
        description: |
          It shall be the minimum value of the application configuration
          option.
        spec-type: int-or-str
      set:
        description: |
          It shall be the set of valid values for the application configuration
          option.
        spec-type: list-int-or-str
      texts:
        description: |
          It shall be a list of constraints specific to this application
          configuration option.  For general constraints, use a link with the
          ${constraint-role:/spec-name} to a constraint item.
        spec-type: requirement-text-list
    description: |
      This set of attributes defines application configuration option
      constraints.  Additional constraints can be added through the links of
      the item using the ${constraint-role:/spec-name}.
    required-attributes: none
spec-name: Application Configuration Option Constraint Set
spec-type: appl-config-option-constraints
type: spec
