SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
copyrights:
- Copyright (C) 2020 embedded brains GmbH (http://www.embedded-brains.de)
enabled-by: true
links:
- role: spec-member
  uid: root
- role: spec-refinement
  spec-key: interface-type
  spec-value: appl-config-group
  uid: interface
spec-description: null
spec-example: null
spec-info:
  dict:
    attributes:
      appl-config-group-description:
        description: |
          This mandatory attribute shall be the description of the application
          configuration group.
        spec-type: str
      appl-config-group-name:
        description: |
          This mandatory attribute defines the application configuration group
          human readable name.
        spec-type: str
      text:
        description: |
          This mandatory attribute states the requirement for the application
          configuration group.
        spec-type: requirement-text
    description: |
      This set of attributes specifies application configuration group
      specification items.
    required-attributes: all
spec-name: Application Configuration Group Item Type
spec-type: appl-config-group
type: spec
