SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
copyrights:
- Copyright (C) 2020 embedded brains GmbH (http://www.embedded-brains.de)
enabled-by: true
links:
- role: spec-member
  uid: root
- role: spec-refinement
  spec-key: type
  spec-value: build
  uid: root
spec-description: null
spec-example: null
spec-info:
  dict:
    attributes:
      build-type:
        description: |
          This mandatory attribute defines the build type.
        spec-type: name
    description: |
      This set of attributes specifies a build item.
    required-attributes: all
spec-name: Build Item Type
spec-type: build
type: spec
