SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
brief: |
  Gets the clock ticks per timeslice configured for this application.
copyrights:
- Copyright (C) 2020 embedded brains GmbH (http://www.embedded-brains.de)
definition:
  default:
    attributes: null
    body: ${/score/watchdog/if/ticks-per-timeslice:/name}
    params: []
    return: null
  variants: []
description: null
enabled-by: true
index-entries: []
interface-type: macro
links:
- role: interface-placement
  uid: header
- role: interface-ingroup
  uid: group
name: rtems_configuration_get_ticks_per_timeslice
notes: |
  See ${/acfg/if/ticks-per-time-slice:/name}.
params: []
return:
  return: |
    Returns the clock ticks per timeslice configured for this application.
  return-values: []
type: interface
