SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
brief: |
  Gets the IDLE task entry of this application.
copyrights:
- Copyright (C) 2020 embedded brains GmbH (http://www.embedded-brains.de)
definition:
  default:
    attributes: null
    body: ${/score/thread/if/idle-body:/name}
    params: []
    return: void *( * )( ${/c/if/uintptr_t:/name} )
  variants: []
description: null
enabled-by: true
index-entries: []
interface-type: macro
links:
- role: interface-placement
  uid: header
- role: interface-ingroup
  uid: group
name: rtems_configuration_get_idle_task
notes: |
  See ${/acfg/if/idle-task-body:/name}.
params: []
return:
  return: |
    Returns the IDLE task entry of this application.
  return-values: []
type: interface
