SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
brief: |
  Indicates if the thread stack allocator is configured to avoid the RTEMS
  Workspace for this application.
copyrights:
- Copyright (C) 2020 embedded brains GmbH (http://www.embedded-brains.de)
definition:
  default:
    attributes: null
    body: ${/score/stack/if/allocator-avoids-workspace:/name}
    params: []
    return: ${/c/if/bool:/name}
  variants: []
description: null
enabled-by: true
index-entries: []
interface-type: macro
links:
- role: interface-placement
  uid: header
- role: interface-ingroup
  uid: group
name: rtems_configuration_get_stack_allocator_avoids_work_space
notes: |
  See ${/acfg/if/task-stack-no-workspace:/name}.
params: []
return:
  return: |
    Returns true, if the thread stack allocator is configured to avoid the
    RTEMS Workspace for this application, otherwise false.
  return-values: []
type: interface
