SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
brief: |
  Returns the number of initial extensions configured for this application.
copyrights:
- Copyright (C) 2020 embedded brains GmbH (http://www.embedded-brains.de)
definition:
  default: ((${/c/if/uint32_t:/name}) ${/score/userext/if/initial-count:/name})
  variants: []
description: null
enabled-by: true
interface-type: macro
links:
- role: interface-placement
  uid: header
- role: interface-ingroup
  uid: group
name: rtems_configuration_get_number_of_initial_extensions
notes: null
params: []
return:
  return: null
  return-values: []
type: interface
