SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
brief: |
  Gets the thread stack allocator free hook configured for this application.
copyrights:
- Copyright (C) 2020 embedded brains GmbH (http://www.embedded-brains.de)
definition:
  default:
    attributes: null
    body: ${/score/stack/if/allocator-free:/name}
    params: []
    return: void ( * )( void * )
  variants: []
description: null
enabled-by: true
index-entries: []
interface-type: macro
links:
- role: interface-placement
  uid: header
- role: interface-ingroup
  uid: group
name: rtems_configuration_get_stack_free_hook
notes: |
  See ${/acfg/if/task-stack-deallocator:/name}.
params: []
return:
  return: |
    Returns the thread stack allocator free hook configured for this
    application.
  return-values: []
type: interface
