SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
brief: |
  Gets the IDLE task body of this application.
copyrights:
- Copyright (C) 2020 embedded brains GmbH & Co. KG
definition:
  default:
    attributes: null
    body: ${/score/thread/if/idle-body:/name}
    params: []
    return: void *( * )( ${/c/if/uintptr_t:/name} )
  variants: []
description: null
enabled-by: true
index-entries: []
interface-type: macro
links:
- role: interface-placement
  uid: header
- role: interface-ingroup
  uid: group
- role: constraint
  uid: /constraint/directive-ctx-any
- role: constraint
  uid: /constraint/directive-no-preempt
name: rtems_configuration_get_idle_task
notes: |
  The IDLE task body is defined by the ${/acfg/if/idle-task-body:/name}
  application configuration option.
params: []
return:
  return: |
    Returns the IDLE task body of this application.
  return-values: []
type: interface
