SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
brief: |
  Gets the configured size in bytes of the memory space used to allocate thread
  stacks for this application.
copyrights:
- Copyright (C) 2020 embedded brains GmbH & Co. KG
definition:
  default:
    attributes: null
    body: null
    params: []
    return: ${/c/if/uintptr_t:/name}
  variants: []
description: null
enabled-by: true
index-entries: []
interface-type: function
links:
- role: interface-placement
  uid: header
- role: interface-ingroup
  uid: group
- role: constraint
  uid: /constraint/directive-not-pre-qualified
- role: constraint
  uid: /constraint/directive-ctx-any
- role: constraint
  uid: /constraint/directive-no-preempt
name: rtems_configuration_get_stack_space_size
notes: |
  The size takes only threads and tasks into account with are known at the
  application configuration time.
params: []
return:
  return: |
    Returns the configured size in bytes of the memory space used to allocate
    thread stacks for this application.
  return-values: []
type: interface
