SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
brief: |
  Gets the number of initial extensions configured for this application.
copyrights:
- Copyright (C) 2020 embedded brains GmbH & Co. KG
definition:
  default:
    attributes: null
    body: ((${/c/if/uint32_t:/name}) ${/score/userext/if/initial-count:/name})
    params: []
    return: ${/c/if/uint32_t:/name}
  variants: []
description: null
enabled-by: true
index-entries: []
interface-type: macro
links:
- role: interface-placement
  uid: header
- role: interface-ingroup
  uid: group
- role: constraint
  uid: /constraint/directive-not-pre-qualified
- role: constraint
  uid: /constraint/directive-ctx-any
- role: constraint
  uid: /constraint/directive-no-preempt
name: rtems_configuration_get_number_of_initial_extensions
notes: |
  The number of initial extensions is defined by the
  ${/acfg/if/initial-extensions:/name} application configuration option and
  related options.
params: []
return:
  return: |
    Returns the number of initial extensions configured for this application.
  return-values: []
type: interface
