SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
brief: |
  Gets the maximum number of Classic API Partitions configured for
  this application.
copyrights:
- Copyright (C) 2020 embedded brains GmbH (http://www.embedded-brains.de)
definition:
  default:
    attributes: null
    body: null
    params: []
    return: ${/c/if/uint32_t:/name}
  variants: []
description: null
enabled-by: true
index-entries: []
interface-type: function
links:
- role: interface-placement
  uid: header-2
- role: interface-ingroup
  uid: group
name: rtems_configuration_get_maximum_partitions
notes: |
  See ${/acfg/if/max-partitions:/name}.
params: []
return:
  return: |
    Returns the maximum number of Classic API Partitions configured
    for this application.
  return-values: []
type: interface
