SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
brief: |
  Gets the maximum number of processors configured for this application.
copyrights:
- Copyright (C) 2020 embedded brains GmbH & Co. KG
definition:
  default:
    attributes: null
    body: ${/score/smp/if/processor-configured-maximum:/name}
    params: []
    return: ${/c/if/uint32_t:/name}
  variants: []
description: null
enabled-by: true
index-entries: []
interface-type: macro
links:
- role: interface-placement
  uid: header
- role: interface-ingroup
  uid: group
- role: constraint
  uid: /constraint/directive-ctx-any
- role: constraint
  uid: /constraint/directive-no-preempt
name: rtems_configuration_get_maximum_processors
notes: |
  The actual number of processors available to the application is returned by
  ${../../scheduler/if/get-processor-maximum:/name} which less than or
  equal to the configured maximum number of processors
  (${/acfg/if/max-processors:/name}).

  In uniprocessor configurations, this macro is a compile time constant which
  evaluates to one.
params: []
return:
  return: |
    Returns the maximum number of processors configured for this
    application.
  return-values: []
type: interface
