SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
brief: |
  Returns the maximum number of Classic API Barriers which are configured for
  this application.
copyrights:
- Copyright (C) 2020 embedded brains GmbH (http://www.embedded-brains.de)
definition:
  default:
    body: null
    params: []
    return: ${/c/if/uint32_t:/name}
  variants: []
description: null
enabled-by: true
interface-type: function
links:
- role: interface-placement
  uid: header-2
- role: interface-ingroup
  uid: group
name: rtems_configuration_get_maximum_barriers
notes: null
params: []
return:
  return: null
  return-values: []
type: interface
