SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
brief: |
  Gets the IDLE task stack size in bytes of this application.
copyrights:
- Copyright (C) 2020 embedded brains GmbH (http://www.embedded-brains.de)
definition:
  default:
    attributes: null
    body: ${/score/thread/if/idle-stack-size:/name}
    params: []
    return: null
  variants: []
description: null
enabled-by: true
index-entries: []
interface-type: macro
links:
- role: interface-placement
  uid: header
- role: interface-ingroup
  uid: group
name: rtems_configuration_get_idle_task_stack_size
notes: |
  See ${/acfg/if/idle-task-stack-size:/name}.
params: []
return:
  return: |
    Returns the IDLE task stack size in bytes of this application.
  return-values: []
type: interface
