SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
brief: |
  Gets the interrupt stack size in bytes of this application.
copyrights:
- Copyright (C) 2020 embedded brains GmbH (http://www.embedded-brains.de)
definition:
  default: ((${/c/if/size_t:/name}) ${/score/isr/if/stack-size:/name})
  variants: []
description: null
enabled-by: true
index-entries: []
interface-type: macro
links:
- role: interface-placement
  uid: header
- role: interface-ingroup
  uid: group
name: rtems_configuration_get_interrupt_stack_size
notes: |
  See ${/acfg/if/interrupt-stack-size:/name}.
params: []
return:
  return: |
    Returns the interrupt stack size in bytes of this application.
  return-values: []
type: interface
