SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
brief: |
  Gets the Classic API Configuration Table of this application.
copyrights:
- Copyright (C) 2020 embedded brains GmbH (http://www.embedded-brains.de)
definition:
  default:
    attributes: null
    body: null
    params: []
    return: const ${api-table:/name} *
  variants: []
description: null
enabled-by: true
index-entries: []
interface-type: function
links:
- role: interface-placement
  uid: header-2
- role: interface-ingroup
  uid: group
- role: constraint
  uid: /constraint/directive-not-pre-qualified
name: rtems_configuration_get_rtems_api_configuration
notes: null
params: []
return:
  return: |
    Returns the pointer to the Classic API Configuration Table of this
    application.
  return-values: []
type: interface
