SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
brief: |
  Gets the number of microseconds per clock tick configured for this
  application.
copyrights:
- Copyright (C) 2020 embedded brains GmbH & Co. KG
definition:
  default:
    attributes: null
    body: ${/score/watchdog/if/microseconds-per-tick:/name}
    params: []
    return: ${/c/if/uint32_t:/name}
  variants: []
description: null
enabled-by: true
index-entries: []
interface-type: macro
links:
- role: interface-placement
  uid: header
- role: interface-ingroup
  uid: group
- role: constraint
  uid: /constraint/directive-ctx-any
- role: constraint
  uid: /constraint/directive-no-preempt
name: rtems_configuration_get_microseconds_per_tick
notes: |
  The number of microseconds per ${/glossary/clock-tick:/term} is defined by
  the ${/acfg/if/microseconds-per-tick:/name} application configuration option.
params: []
return:
  return: |
    Returns the number of microseconds per clock tick configured for this
    application.
  return-values: []
type: interface
