SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
brief: |
  Gets the task stack allocator allocate hook configured for this application.
copyrights:
- Copyright (C) 2020 embedded brains GmbH & Co. KG
definition:
  default:
    attributes: null
    body: ${/score/stack/if/allocator-allocate:/name}
    params: []
    return: void *( * )( ${/c/if/size_t:/name} )
  variants: []
description: null
enabled-by: true
index-entries: []
interface-type: macro
links:
- role: interface-placement
  uid: header
- role: interface-ingroup
  uid: group
- role: constraint
  uid: /constraint/directive-ctx-any
- role: constraint
  uid: /constraint/directive-no-preempt
name: rtems_configuration_get_stack_allocate_hook
notes: |
  The task stack allocator allocate hook is defined by the
  ${/acfg/if/task-stack-allocator:/name} application configuration option.
params: []
return:
  return: |
    Returns the task stack allocator allocate hook configured for this
    application.
  return-values: []
type: interface
