SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
brief: |
  Returns the RTEMS Workspace size in bytes configured for this application.
copyrights:
- Copyright (C) 2020 embedded brains GmbH (http://www.embedded-brains.de)
definition:
  default: |
    (${/score/wkspace/if/size:/name} +
      (${get-stack-allocator-avoids-work-space:/name}() ?
        0 : ${get-stack-space-size:/name}()))
  variants: []
description: null
enabled-by: true
interface-type: macro
links:
- role: interface-placement
  uid: header
- role: interface-ingroup
  uid: group
name: rtems_configuration_get_work_space_size
notes: null
params: []
return:
  return: null
  return-values: []
type: interface
