SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
brief: |
  Returns the pointer to the MPCI configuration table configured for this
  application.
copyrights:
- Copyright (C) 2020 embedded brains GmbH (http://www.embedded-brains.de)
definition:
  default: ${/c/if/null:/name}
  variants:
  - definition: ( &${/score/mpci/if/configuration:/name} )
    enabled-by: defined(${/build-options/if/multiprocessing:/name})
description: null
enabled-by: true
index-entries: []
interface-type: macro
links:
- role: interface-placement
  uid: header
- role: interface-ingroup
  uid: group
name: rtems_configuration_get_user_multiprocessing_table
notes: null
params: []
return:
  return: null
  return-values: []
type: interface
