SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
brief: |
  Gets the resource number of ${/rtems/dpmem/if/group:/name} objects configured
  for this application.
copyrights:
- Copyright (C) 2020 embedded brains GmbH & Co. KG
definition:
  default:
    attributes: null
    body: null
    params: []
    return: ${/c/if/uint32_t:/name}
  variants: []
description: null
enabled-by: true
index-entries: []
interface-type: function
links:
- role: interface-placement
  uid: header-2
- role: interface-ingroup
  uid: group
- role: constraint
  uid: /constraint/directive-ctx-any
- role: constraint
  uid: /constraint/directive-no-preempt
name: rtems_configuration_get_maximum_ports
notes: |
  The resource number is defined by the ${/acfg/if/max-ports:/name}
  application configuration option.  See also ${resource-is-unlimited:/name}
  and ${resource-maximum-per-allocation:/name}.
params: []
return:
  return: |
    Returns the resource number of ${/rtems/dpmem/if/group:/name} objects
    configured for this application.
  return-values: []
type: interface
