SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
brief: |
  Gets the number of microseconds per clock tick configured for this
  application.
copyrights:
- Copyright (C) 2020 embedded brains GmbH (http://www.embedded-brains.de)
definition:
  default:
    attributes: null
    body: ${/score/watchdog/if/microseconds-per-tick:/name}
    params: []
    return: ${/c/if/uint32_t:/name}
  variants: []
description: null
enabled-by: true
index-entries: []
interface-type: macro
links:
- role: interface-placement
  uid: header
- role: interface-ingroup
  uid: group
name: rtems_configuration_get_microseconds_per_tick
notes: |
  See ${/acfg/if/microseconds-per-tick:/name}.
params: []
return:
  return: |
    Returns the number of microseconds per clock tick configured for this
    application.
  return-values: []
type: interface
