SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
brief: |
  Returns the ticks per timeslice configured for this application.
copyrights:
- Copyright (C) 2020 embedded brains GmbH (http://www.embedded-brains.de)
definition:
  default: ${/score/watchdog/if/ticks-per-timeslice:/name}
  variants: []
description: null
enabled-by: true
interface-type: macro
links:
- role: interface-placement
  uid: header
- role: interface-ingroup
  uid: group
name: rtems_configuration_get_ticks_per_timeslice
notes: null
params: []
return:
  return: null
  return-values: []
type: interface
