SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
brief: |
  Returns true, if the RTEMS Workspace is zeroed during system initialization
  for this application, otherwise returns false.
copyrights:
- Copyright (C) 2020 embedded brains GmbH (http://www.embedded-brains.de)
definition:
  default: ${/score/memory/if/zero-before-use:/name}
  variants: []
description: null
enabled-by: true
index-entries: []
interface-type: macro
links:
- role: interface-placement
  uid: header
- role: interface-ingroup
  uid: group
name: rtems_configuration_get_do_zero_of_workspace
notes: null
params: []
return:
  return: null
  return-values: []
type: interface
