SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
brief: |
  Gets the thread stack allocator allocate hook configured for this
  application.
copyrights:
- Copyright (C) 2020 embedded brains GmbH (http://www.embedded-brains.de)
definition:
  default:
    attributes: null
    body: ${/score/stack/if/allocator-allocate:/name}
    params: []
    return: null
  variants: []
description: null
enabled-by: true
index-entries: []
interface-type: macro
links:
- role: interface-placement
  uid: header
- role: interface-ingroup
  uid: group
name: rtems_configuration_get_stack_allocate_hook
notes: |
  See ${/acfg/if/task-stack-allocator:/name}.
params: []
return:
  return: |
    Returns the thread stack allocator allocate hook configured for this
    application.
  return-values: []
type: interface
