SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
brief: |
  Gets the RTEMS Workspace size in bytes configured for this application.
copyrights:
- Copyright (C) 2020 embedded brains GmbH & Co. KG
definition:
  default:
    attributes: null
    body: |
      ( ${/score/wkspace/if/size:/name} +
        ( ${get-stack-allocator-avoids-work-space:/name}() ?
          0 : ${get-stack-space-size:/name}() ) )
    params: []
    return: ${/c/if/uintptr_t:/name}
  variants: []
description: null
enabled-by: true
index-entries: []
interface-type: macro
links:
- role: interface-placement
  uid: header
- role: interface-ingroup
  uid: group
- role: constraint
  uid: /constraint/directive-not-pre-qualified
- role: constraint
  uid: /constraint/directive-ctx-any
- role: constraint
  uid: /constraint/directive-no-preempt
name: rtems_configuration_get_work_space_size
notes: null
params: []
return:
  return: |
    Returns the RTEMS Workspace size in bytes configured for this application.
  return-values: []
type: interface
