SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
brief: |
  Gets the MPCI configuration table configured for this application.
copyrights:
- Copyright (C) 2020 embedded brains GmbH & Co. KG
definition:
  default:
    attributes: null
    body: ${/c/if/null:/name}
    params: []
    return: const ${/score/mpci/if/configuration-type:/name} *
  variants:
  - definition:
      attributes: null
      body: ( &${/score/mpci/if/configuration:/name} )
      params: []
      return: const ${/score/mpci/if/configuration-type:/name} *
    enabled-by: defined(${/build-options/if/multiprocessing:/name})
description: null
enabled-by: true
index-entries: []
interface-type: macro
links:
- role: interface-placement
  uid: header
- role: interface-ingroup
  uid: group
- role: constraint
  uid: /constraint/directive-not-pre-qualified
- role: constraint
  uid: /constraint/directive-ctx-any
- role: constraint
  uid: /constraint/directive-no-preempt
name: rtems_configuration_get_user_multiprocessing_table
notes: null
params: []
return:
  return: |
    Returns a pointer to the MPCI configuration table configured for this
    application.
  return-values: []
type: interface
