SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
brief: |
  Augments the resource number so that it indicates an unlimited resource.
copyrights:
- Copyright (C) 2020 embedded brains GmbH (http://www.embedded-brains.de)
definition:
  default:
    attributes: null
    body: ( ( ${.:/params[0]/name} ) | ${unlimited-objects:/name} )
    params:
    - ${/c/if/uint32_t:/name} ${.:/params[0]/name}
    return: ${/c/if/uint32_t:/name}
  variants: []
description: null
enabled-by: true
index-entries: []
interface-type: macro
links:
- role: interface-placement
  uid: header
- role: interface-ingroup
  uid: group
- role: constraint
  uid: /constraint/directive-not-pre-qualified
- role: constraint
  uid: /constraint/directive-ctx-const
- role: constraint
  uid: /constraint/directive-no-preempt
name: rtems_resource_unlimited
notes: |
  This directive should be used to configure unlimited objects, see
  ${/doc/if/config-unlimited-objects:/name}.
params:
- description: is the resource number to augment.
  dir: null
  name: _resource
return:
  return: |
    Returns the resource number augmented to indicate an unlimited resource.
  return-values: []
type: interface
