SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
brief: |
  Augments the resource number so that it indicates an unlimited resource.
copyrights:
- Copyright (C) 2020 embedded brains GmbH (http://www.embedded-brains.de)
definition:
  default: ( ( ${.:/params[0]/name} ) | ${unlimited-objects:/name} )
  variants: []
description: null
enabled-by: true
index-entries: []
interface-type: macro
links:
- role: interface-placement
  uid: header
- role: interface-ingroup
  uid: group
- role: constraint
  uid: /constraint/directive-not-pre-qualified
name: rtems_resource_unlimited
notes: |
  This function is implemented as a macro and can be used to define compile
  time constants.
params:
- description: is the resource number to augment.
  dir: null
  name: _resource
return:
  return: |
    Returns the resource number augmented to indicate an unlimited resource.
  return-values: []
type: interface
