SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
brief: |
  Gets the maximum number per allocation of a resource number.
copyrights:
- Copyright (C) 2020 embedded brains GmbH & Co. KG
definition:
  default:
    attributes: null
    body: |
      ${/score/object/if/maximum-per-allocation:/name}( ${.:/params[0]/name} )
    params:
    - ${/c/if/uint32_t:/name} ${.:/params[0]/name}
    return: ${/c/if/uint32_t:/name}
  variants: []
description: null
enabled-by: true
index-entries: []
interface-type: macro
links:
- role: interface-placement
  uid: header
- role: interface-ingroup
  uid: group
- role: constraint
  uid: /constraint/directive-not-pre-qualified
- role: constraint
  uid: /constraint/directive-ctx-const
- role: constraint
  uid: /constraint/directive-no-preempt
name: rtems_resource_maximum_per_allocation
notes: null
params:
- description: is the resource number.
  dir: null
  name: _resource
return:
  return: |
    Returns the maximum number per allocation of a resource number.
  return-values: []
type: interface
