SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
brief: |
  Returns the resource maximum number per allocation.
copyrights:
- Copyright (C) 2020 embedded brains GmbH (http://www.embedded-brains.de)
definition:
  default: ${/score/object/if/maximum-per-allocation:/name}(${.:/params[0]/name})
  variants: []
description: null
enabled-by: true
interface-type: macro
links:
- role: interface-placement
  uid: header
- role: interface-ingroup
  uid: group
name: rtems_resource_maximum_per_allocation
notes: null
params:
- description: is the resource number.
  dir: null
  name: _resource
return:
  return: null
  return-values: []
type: interface
