SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
brief: |
  Thread stack allocator initialization handlers shall have this type.
copyrights:
- Copyright (C) 2020 embedded brains GmbH (http://www.embedded-brains.de)
definition:
  default: ${/score/stack/if/allocator-initialize-type:/name} ${.:/name}
  variants: []
description: null
enabled-by: true
interface-type: typedef
links:
- role: interface-placement
  uid: header
- role: interface-ingroup
  uid: group
name: rtems_stack_allocate_init_hook
notes: null
type: interface
