SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
brief: |
  A task stack allocator free handler shall have this type.
copyrights:
- Copyright (C) 2020 embedded brains GmbH (http://www.embedded-brains.de)
definition:
  default: ${/score/stack/if/allocator-free-type:/name} ${.:/name}
  variants: []
description: null
enabled-by: true
index-entries: []
interface-type: typedef
links:
- role: interface-placement
  uid: header
- role: interface-ingroup
  uid: group
name: rtems_stack_free_hook
notes: null
params: []
return: null
type: interface
