SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
brief: |
  This flag is used in augment a resource number so that it indicates an
  unlimited resource.
copyrights:
- Copyright (C) 2020 embedded brains GmbH (http://www.embedded-brains.de)
definition:
  default: ${/score/object/if/unlimited-objects:/name}
  variants: []
description: null
enabled-by: true
index-entries: []
interface-type: define
links:
- role: interface-placement
  uid: header
- role: interface-ingroup
  uid: group
- role: constraint
  uid: /constraint/directive-not-pre-qualified
name: RTEMS_UNLIMITED_OBJECTS
notes: null
type: interface
