SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
copyrights:
- Copyright (C) 2020 embedded brains GmbH (http://www.embedded-brains.de)
- Copyright (C) 1989, 2008 On-Line Applications Research Corporation (OAR)
enabled-by: true
interface-brief: |
  This status code indicates that multiprocessing is not configured.
interface-definition:
  default: '2'
  variants: []
interface-description: null
interface-name: RTEMS_MP_NOT_CONFIGURED
interface-notes: null
interface-type: enumerator
links: []
type: interface
