SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
copyrights:
- Copyright (C) 2020 embedded brains GmbH (http://www.embedded-brains.de)
enabled-by: true
interface-type: variable
links:
- role: interface-placement
  uid: header
name: _SMP_Processor_configured_maximum
type: interface
