SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
copyrights:
- Copyright (C) 2021 embedded brains GmbH & Co. KG
enabled-by: true
functional-type: function
links:
- role: interface-function
  uid: ../if/disable-bsp-settings
- role: requirement-refinement
  uid: group
rationale: null
references: []
requirement-type: functional
text: |
  The application configuration option shall disable the use of
  ${/glossary/bsp:/term}-provided default values for application configuration
  options.
type: requirement
