settings:
  digits: 3
  parent: RTEMS-ACFG
  prefix: RTEMS-ACFG-OPT
  sep: '-'
attributes:
  defaults:
    SPDX-License-Identifier: CC-BY-SA-4.0
    appl-config-option-type: feature-enable
    appl-config-option-description: |
      Text.
    appl-config-option-index: []
    appl-config-option-name: CONFIGURE_NEW
    appl-config-option-notes: |
      None.
    copyrights:
    - Copyright (C) 2020 John Doe
    enabled-by: []
    interface-type: appl-config-option
    type: interface
  reviewed:
  - enabled-by
  - interface-type
  - type
