SPDX-License-Identifier: CC-BY-SA-4.0
appl-config-option-description: |
  In case this configuration option is defined, then the following BSP related
  configuration options are undefined:

  - :ref:`BSP_IDLE_TASK_BODY`

  - :ref:`BSP_IDLE_TASK_STACK_SIZE`

  - :ref:`BSP_INITIAL_EXTENSION`

  - :ref:`BSP_INTERRUPT_STACK_SIZE`

  - :ref:`CONFIGURE_BSP_PREREQUISITE_DRIVERS`

  - :ref:`CONFIGURE_MALLOC_BSP_SUPPORTS_SBRK`
appl-config-option-index: []
appl-config-option-name: CONFIGURE_DISABLE_BSP_SETTINGS
appl-config-option-notes: null
appl-config-option-type: feature-enable
copyrights:
- Copyright (C) 1988, 2008 On-Line Applications Research Corporation (OAR)
enabled-by: true
interface-type: appl-config-option
links:
- role: appl-config-group-member
  uid: ../bsp
text: ''
type: interface
