SPDX-License-Identifier: CC-BY-SA-4.0
copyrights:
- Copyright (C) 2021 embedded brains GmbH & Co. KG
enabled-by: true
links:
- role: interface-function
  uid: ../if/configured-minimum-stack-size
functional-type: function
rationale: |
  Using a value of zero will let ${../if/create:/name} select the configured
  minimum task stack size.
references: []
requirement-type: functional
text: |
  The ${../if/configured-minimum-stack-size:/name} constant shall expand to a
  constant expression which evaluates to the value of zero.
type: requirement
