SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
copyrights:
- Copyright (C) 2020 embedded brains GmbH (http://www.embedded-brains.de
enabled-by: true
links: []
requirement-type: configuration
text: |
  The system shall provide configuration options to the application to set
  configurable system parameters at link time.
type: requirement
