active: true
derived: false
header: ''
level: 1.3
links: []
normative: true
ref: ''
requirement-type: configuration
reviewed: _UBhDG0InGYgvxZhg-cUyh3flgj_xCc4GH8Rs0qjazE=
text: |
  The system shall provide configuration options to the application to set
  configurable system parameters at link time.
type: requirement
