SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
copyrights:
- Copyright (C) 2021 embedded brains GmbH & Co. KG
enabled-by: true
index-entries: []
interface-type: unspecified-group
links:
- role: interface-placement
  uid: domain
- role: interface-ingroup
  uid: group
name: Clustered Scheduler Configuration
references:
- identifier: ConfigurationSchedulersClustered
  name: c-user
  type: document
- identifier: https://docs.rtems.org/branches/master/c-user/config/scheduler-clustered.html
  type: url
type: interface
