SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
copyrights:
- Copyright (C) 2021 embedded brains GmbH (http://www.embedded-brains.de)
enabled-by: true
index-entries: []
interface-type: unspecified-group
links:
- role: interface-placement
  uid: domain
- role: interface-ingroup
  uid: group
name: Unlimited Objects
references:
- identifier: ConfigUnlimitedObjects
  name: c-user
  type: document
- identifier: https://docs.rtems.org/branches/master/c-user/config/intro.html#unlimited-objects
  type: url
type: interface
