SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
brief: |
  This attribute constant is used to indicate that the Classic API Task object
  shall be an application task.
copyrights:
- Copyright (C) 2020 embedded brains GmbH (http://www.embedded-brains.de)
- Copyright (C) 2008 On-Line Applications Research Corporation (OAR)
definition:
  default: '0x00000000'
  variants: []
description: null
enabled-by: true
interface-type: define
links:
- role: interface-placement
  uid: header
- role: interface-ingroup
  uid: group
name: RTEMS_APPLICATION_TASK
notes: null
type: interface
