SPDX-License-Identifier: CC-BY-SA-4.0
copyrights:
- Copyright (C) 2021 embedded brains GmbH & Co. KG
enabled-by: true
links:
- role: interface-function
  uid: ../if/get-ticks-per-timeslice
functional-type: function
rationale: |
  The directive may be used to check the setting of the
  ${/acfg/if/ticks-per-time-slice:/name} application configuration option.
references: []
requirement-type: functional
text: |
  The ${../if/get-ticks-per-timeslice:/name} directive shall return the number
  of ${/glossary/clock-tick:/plural} per timeslice.
type: requirement
