SPDX-License-Identifier: CC-BY-SA-4.0
copyrights:
- Copyright (C) 2021 embedded brains GmbH (http://www.embedded-brains.de)
enabled-by: true
links:
- role: interface-function
  uid: ../if/get-ticks-per-timeslice
functional-type: function
rationale: null
references: []
requirement-type: functional
text: |
  The ${../if/get-ticks-per-timeslice:/name} directive shall return the number
  of ${/glossary/clock-tick:/plural} per timeslice configured by
  ${/acfg/if/ticks-per-time-slice:/name}.
type: requirement
