SPDX-License-Identifier: CC-BY-SA-4.0
copyrights:
- Copyright (C) 2021 embedded brains GmbH & Co. KG
enabled-by: true
links:
- role: interface-function
  uid: ../if/get-maximum-processors
functional-type: function
rationale: |
  The directive may be used to check the setting of the
  ${/acfg/if/max-processors:/name} application configuration option.  The
  maximum number of processors which are actually available for use by the
  application is returned by
  ${../../scheduler/if/get-processor-maximum:/name}.
references: []
requirement-type: functional
text: |
  The ${../if/get-maximum-processors:/name} directive shall return the maximum
  number of processors which can be managed by the system.
type: requirement
