SPDX-License-Identifier: CC-BY-SA-4.0
copyrights:
- Copyright (C) 2021 embedded brains GmbH & Co. KG
enabled-by: true
links:
- role: interface-function
  uid: ../if/get-maximum-message-queues
functional-type: function
rationale: |
  The directive may be used to check the setting of the
  ${/acfg/if/max-message-queues:/name} application configuration option.
references: []
requirement-type: functional
text: |
  The ${../if/get-maximum-message-queues:/name} directive shall return the
  maximum number of objects managed by the ${../../message/if/group:/name} that
  can be concurrently active.
type: requirement
