SPDX-License-Identifier: CC-BY-SA-4.0
copyrights:
- Copyright (C) 2021 embedded brains GmbH & Co. KG
enabled-by: true
links:
- role: interface-function
  uid: ../if/get-idle-task
functional-type: function
rationale: |
  The directive may be used to check the setting of the
  ${/acfg/if/idle-task-body:/name} application configuration option.
references: []
requirement-type: functional
text: |
  The ${../if/get-idle-task:/name} directive shall return the address of task
  body executed by each ${/glossary/idletask:/term}.
type: requirement
