SPDX-License-Identifier: CC-BY-SA-4.0
copyrights:
- Copyright (C) 2021 embedded brains GmbH (http://www.embedded-brains.de)
enabled-by: true
links:
- role: interface-function
  uid: ../if/get-idle-task
functional-type: function
rationale: null
references: []
requirement-type: functional
text: |
  The ${../if/get-idle-task:/name} directive shall return the IDLE task body
  configured by ${/acfg/if/idle-task-body:/name}.
type: requirement
