SPDX-License-Identifier: CC-BY-SA-4.0
copyrights:
- Copyright (C) 2021 embedded brains GmbH & Co. KG
enabled-by: true
links:
- role: interface-function
  uid: ../if/get-stack-allocate-hook
functional-type: function
rationale: |
  The directive may be used to check the setting of the
  ${/acfg/if/task-stack-allocator:/name} application configuration option.
references: []
requirement-type: functional
text: |
  The ${../if/get-stack-allocate-hook:/name} directive shall return the address
  of the task stack allocator which is used to allocate the stack for a task
  which is not an ${/glossary/idletask:/term}.
type: requirement
