SPDX-License-Identifier: CC-BY-SA-4.0
copyrights:
- Copyright (C) 2021 embedded brains GmbH (http://www.embedded-brains.de)
enabled-by: true
links:
- role: interface-function
  uid: ../if/get-interrupt-stack-size
functional-type: function
rationale: null
references: []
requirement-type: functional
text: |
  The ${../if/get-interrupt-stack-size:/name} directive shall return the
  interrupt stack size configured by ${/acfg/if/interrupt-stack-size:/name}.
type: requirement
