SPDX-License-Identifier: CC-BY-SA-4.0
copyrights:
- Copyright (C) 2021 embedded brains GmbH (http://www.embedded-brains.de)
enabled-by: true
links:
- role: interface-function
  uid: ../if/get-stack-allocator-avoids-work-space
functional-type: function
rationale: null
references: []
requirement-type: functional
text: |
  The ${../if/get-stack-allocator-avoids-work-space:/name} directive shall
  return the option value configured by
  ${/acfg/if/task-stack-no-workspace:/name}.
type: requirement
