SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
copyrights:
- Copyright (C) 1988, 1998 On-Line Applications Research Corporation (OAR)
enabled-by: true
glossary-type: term
links:
- role: glossary-member
  uid: ../glossary-general
term: application
text: |
  In this document, software which makes use of RTEMS.
type: glossary
