SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
copyrights:
- Copyright (C) 1988, 1998 On-Line Applications Research Corporation (OAR)
enabled-by: true
glossary-type: term
links:
- role: glossary-member
  uid: ../glossary-general
term: local
text: |
  An object which was created with the LOCAL attribute and is accessible
  only on the node it was created and resides upon.  In a single processor
  configuration, all objects are local.
type: glossary
