SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
brief: |
  This status code indicates that multiprocessing was not configured.
copyrights:
- Copyright (C) 2020 embedded brains GmbH (http://www.embedded-brains.de)
- Copyright (C) 1989, 2008 On-Line Applications Research Corporation (OAR)
definition:
  default: '2'
  variants: []
description: null
enabled-by: true
index-entries: []
interface-type: enumerator
links: []
name: RTEMS_MP_NOT_CONFIGURED
notes: null
type: interface
