SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
brief: |
  This task mode constant represents the default mode set.
copyrights:
- Copyright (C) 2020 embedded brains GmbH & Co. KG
- Copyright (C) 2008 On-Line Applications Research Corporation (OAR)
definition:
  default: '0x00000000'
  variants: []
description: null
enabled-by: true
index-entries: []
interface-type: define
links:
- role: interface-placement
  uid: header
- role: interface-ingroup
  uid: group
name: RTEMS_DEFAULT_MODES
notes: null
type: interface
