SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
copyrights:
- Copyright (C) 2021 embedded brains GmbH & Co. KG
enabled-by: true
index-entries: []
interface-type: unspecified-enumerator
links:
- role: interface-placement
  uid: fatal-header
- role: interface-ingroup
  uid: group-fatal
name: LEON3_FATAL_INVALID_CACHE_CONFIG_BOOT_PROCESSOR
references: []
type: interface
