SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
copyrights:
- Copyright (C) 2021 embedded brains GmbH (http://www.embedded-brains.de)
enabled-by: true
index-entries: []
interface-type: unspecified-define
links:
- role: interface-placement
  uid: header
- role: interface-ingroup
  uid: group-fatal
name: LEON3_FATAL_INVALID_CACHE_CONFIG_BOOT_PROCESSOR
references: {}
type: interface
