SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
appl-config-option-type: integer
constraints:
  max: ${max-tasks:/name}
  min: 0
copyrights:
- Copyright (C) 2020 embedded brains GmbH (http://www.embedded-brains.de)
default-value: 0
description: |
  The value of this configuration option defines the count of Classic API Tasks
  which are created by ${../rtems/tasks/create-from-config:/name}.
enabled-by: true
index-entries: []
interface-type: appl-config-option
links:
- role: appl-config-group-member
  uid: group-classic
name: CONFIGURE_TASKS_CREATED_FROM_CONFIG
notes: |
  By default, the calculation for the required memory in the RTEMS Workspace for
  tasks assumes that all Classic API Tasks are created by
  ${../rtems/tasks/create:/name}.  This configuration option can be used to
  reduce the required memory for the system-provided task storage
  areas since tasks created by ${../rtems/tasks/create-from-config:/name} use a
  user-provided task storage area.
text: ''
type: interface
