SPDX-License-Identifier: CC-BY-SA-4.0
copyrights:
- Copyright (C) 1988, 1998 On-Line Applications Research Corporation (OAR)
enabled-by: true
glossary-term: application
glossary-type: term
links:
- role: null
  uid: ../general
text: |
  In this document, software which makes use of RTEMS.
type: glossary
