SPDX-License-Identifier: CC-BY-SA-4.0
copyrights:
- Copyright (C) 1988, 1998 On-Line Applications Research Corporation (OAR)
enabled-by: []
glossary-term: Configuration Table
glossary-type: term
links:
- role: null
  uid: ../general
text: |
  A table which contains information used to tailor RTEMS for a particular
  application.
type: glossary
