SPDX-License-Identifier: CC-BY-SA-4.0
copyrights:
- Copyright (C) 1988, 1998 On-Line Applications Research Corporation (OAR)
enabled-by: true
glossary-type: term
links:
- role: glossary-member
  uid: ../general
term: Multiprocessor Configuration Table
text: |
  The data structure defining the characteristics of the multiprocessor
  target system with which RTEMS will communicate.
type: glossary
