SPDX-License-Identifier: CC-BY-SA-4.0
active: true
copyrights:
- Copyright (C) 1988, 1998 On-Line Applications Research Corporation (OAR)
derived: false
enabled-by: []
glossary-term: Multiprocessor Configuration Table
glossary-type: term
header: ''
level: 1.92
links:
- RTEMS-GLOS-GENERAL: y-DGLwoqVNRBlzUau_mx_yR3iKlhE02h2mRxK7VkLQE=
normative: true
ref: ''
reviewed: VR4vsucTs4K-JmGMqPdZGuPEDOjh9KhHWsDO8zcOPvM=
text: |
  The data structure defining the characteristics of the multiprocessor
  target system with which RTEMS will communicate.
type: glossary
