SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
brief: |
  Returns the number of milliseconds per tick configured for this application.
copyrights:
- Copyright (C) 2020 embedded brains GmbH (http://www.embedded-brains.de)
definition:
  default: (${/if/impl/watchdog/microseconds-per-tick:/name} / 1000)
  variants: []
description: null
enabled-by: true
interface-type: macro
links:
- role: interface-placement
  uid: header
- role: interface-ingroup
  uid: /groups/api/config
name: rtems_configuration_get_milliseconds_per_tick
notes: null
params: []
return:
  return: null
  return-values: []
type: interface
