SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
copyrights:
- Copyright (C) 2020 embedded brains GmbH (http://www.embedded-brains.de)
enabled-by: true
interface-brief: |
  Returns the RTEMS Workspace size in bytes configured for this application.
interface-definition:
  default: |
    (${/if/impl/wkspace/size:/interface-name} +
      (${get-stack-allocator-avoids-work-space:/interface-name}() ?
        0 : ${get-stack-space-size:/interface-name}()))
  variants: []
interface-description: null
interface-name: rtems_configuration_get_work_space_size
interface-notes: null
interface-params: []
interface-return:
  return: null
  return-values: []
interface-type: macro
links:
- role: interface-placement
  uid: header
- role: interface-ingroup
  uid: /groups/api/config
type: interface
