SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
copyrights:
- Copyright (C) 2020 embedded brains GmbH (http://www.embedded-brains.de)
enabled-by: true
interface-brief: |
  Returns the maximum number of processors which are configured for this
  application.
interface-definition:
  default: ${/if/impl/smp/processor-configured-maximum:/interface-name}
  variants: []
interface-description: null
interface-name: rtems_configuration_get_maximum_processors
interface-notes: |
  The actual number of processors available for the application will be less
  than or equal to the configured maximum number of processors.

  On uniprocessor configurations this macro is a compile time constant which
  evaluates to one.
interface-params: []
interface-return:
  return: null
  return-values: []
interface-type: macro
links:
- role: interface-placement
  uid: header
- role: interface-ingroup
  uid: /groups/api/config
type: interface
