SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
copyrights:
- Copyright (C) 2020 embedded brains GmbH (http://www.embedded-brains.de)
enabled-by: true
interface-brief: |
  Returns the ticks per timeslice configured for this application.
interface-definition:
  default: ${/if/impl/watchdog/ticks-per-timeslice:/interface-name}
  variants: []
interface-description: null
interface-name: rtems_configuration_get_ticks_per_timeslice
interface-notes: null
interface-params: []
interface-return:
  return: null
  return-values: []
interface-type: macro
links:
- role: interface-placement
  uid: header
- role: interface-ingroup
  uid: /groups/api/config
type: interface
