SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
copyrights:
- Copyright (C) 2020 embedded brains GmbH (http://www.embedded-brains.de)
enabled-by: true
interface-brief: |
  Returns the pointer to the MPCI configuration table configured for this
  application.
interface-definition:
  default: ${/if/c/null:/interface-name}
  variants:
  - definition: ${/if/impl/mpci/configuration:/interface-name}
    enabled-by: defined(${/if/build-options/multiprocessing:/interface-name})
interface-description: null
interface-name: rtems_configuration_get_user_multiprocessing_table
interface-notes: null
interface-params: []
interface-return:
  return: null
  return-values: []
interface-type: macro
links:
- role: interface-placement
  uid: header
- role: interface-ingroup
  uid: /groups/api/config
type: interface
