SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
copyrights:
- Copyright (C) 2020 embedded brains GmbH (http://www.embedded-brains.de)
enabled-by: true
interface-brief: |
  Returns true, if the workspace is zeroed during system initialization,
  otherwise returns false.
interface-definition:
  default: ${/if/impl/memory/zero-before-use:/interface-name}
  variants: []
interface-description: null
interface-name: rtems_configuration_get_do_zero_of_workspace
interface-notes: null
interface-params: []
interface-return:
  return: null
  return-values: []
interface-type: macro
links:
- role: interface-placement
  uid: header
- role: interface-ingroup
  uid: /groups/api/config
type: interface
