SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
copyrights:
- Copyright (C) 2020 embedded brains GmbH (http://www.embedded-brains.de)
enabled-by: true
interface-brief: |
  Returns the configured interrupt stack size in bytes of this application.
interface-definition:
  default: ((${/if/c/size_t:/interface-name}) ${/if/impl/isr/stack-size:/interface-name})
  variants: []
interface-description: null
interface-name: rtems_configuration_get_interrupt_stack_size
interface-notes: null
interface-params: []
interface-return:
  return: null
  return-values: []
interface-type: macro
links:
- role: interface-placement
  uid: header
- role: interface-ingroup
  uid: /groups/api/config
type: interface
