SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
brief: |
  Returns the pointer to the Classic API Configuration Table of this application.
copyrights:
- Copyright (C) 2020 embedded brains GmbH (http://www.embedded-brains.de)
definition:
  default:
    params: []
    return: const rtems_api_configuration_table *
  variants: []
description: null
enabled-by: true
interface-type: function
links:
- role: interface-placement
  uid: header-2
- role: interface-ingroup
  uid: /groups/api/config
name: rtems_configuration_get_rtems_api_configuration
notes: null
params: []
return:
  return: null
  return-values: []
type: interface
