SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
brief: |
  Returns the thread stack space size in bytes of configured for this
  application.
copyrights:
- Copyright (C) 2020 embedded brains GmbH (http://www.embedded-brains.de)
definition:
  default:
    params: []
    return: ${/if/c/uintptr_t:/name}
  variants: []
description: null
enabled-by: true
interface-type: function
links:
- role: interface-placement
  uid: header
- role: interface-ingroup
  uid: /groups/api/config
name: rtems_configuration_get_stack_space_size
notes: null
params: []
return:
  return: null
  return-values: []
type: interface
