SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
brief: |
  Returns true, if the RTEMS Workspace and C Program Heap are unified,
  otherwise returns false.
copyrights:
- Copyright (C) 2020 embedded brains GmbH (http://www.embedded-brains.de)
definition:
  default: ${/if/impl/wkspace/is-unified:/name}
  variants: []
description: null
enabled-by: true
interface-type: macro
links:
- role: interface-placement
  uid: header
- role: interface-ingroup
  uid: group
name: rtems_configuration_get_unified_work_area
notes: null
params: []
return:
  return: null
  return-values: []
type: interface
