SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
brief: |
  This group contains defines and macros to create an application configuration
  as well as functions to get values of the application configuration.
copyrights:
- Copyright (C) 2020 embedded brains GmbH (http://www.embedded-brains.de)
description: null
enabled-by: true
identifier: RTEMSAPIConfig
interface-type: group
links:
- role: interface-placement
  uid: header
- role: interface-ingroup
  uid: ../../api
name: Application Configuration
text: |
  The API shall provide an interface to the application configuration.
type: interface
