SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
copyrights:
- Copyright (C) 2020 embedded brains GmbH (http://www.embedded-brains.de)
enabled-by: true
interface-brief: |
  Returns true, if the resource is unlimited, otherwise returns false.
interface-definition:
  default: ${/if/impl/object/is-unlimited:/interface-name}(${.:/interface-params[0]/name})
  variants: []
interface-description: null
interface-name: rtems_resource_is_unlimited
interface-notes: null
interface-params:
- description: is the resource number.
  dir: null
  name: _resource
interface-return:
  return: null
  return-values: []
interface-type: macro
links:
- role: interface-placement
  uid: header
- role: interface-ingroup
  uid: /groups/api/config
type: interface
