SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
brief: |
  The thread stack allocator free handler.
copyrights:
- Copyright (C) 2020 embedded brains GmbH (http://www.embedded-brains.de)
definition:
  default: ${/if/impl/stack/allocator-free-type:/name} ${.:/name}
  variants: []
description: null
enabled-by: true
interface-type: typedef
links:
- role: interface-placement
  uid: header
- role: interface-ingroup
  uid: /groups/api/config
name: rtems_stack_free_hook
notes: null
type: interface
