SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
copyrights:
- Copyright (C) 2020 embedded brains GmbH (http://www.embedded-brains.de)
enabled-by: true
interface-brief: |
  The thread stack allocator initialization handler.
interface-definition:
  default: ${/if/impl/stack/allocator-initialize-type:/interface-name} ${.:/interface-name}
  variants: []
interface-description: null
interface-name: rtems_stack_allocate_init_hook
interface-notes: null
interface-type: typedef
links:
- role: interface-placement
  uid: header
- role: interface-ingroup
  uid: /groups/api/config
type: interface
