SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
copyrights:
- Copyright (C) 2020 embedded brains GmbH (http://www.embedded-brains.de)
enabled-by: true
interface-brief: |
  This flag is used in resource numbers to indicate an unlimited resource.
interface-definition:
  default: ${/if/impl/object/unlimited-objects:/interface-name}
  variants: []
interface-description: null
interface-name: RTEMS_UNLIMITED_OBJECTS
interface-notes: null
interface-type: define
links:
- role: interface-placement
  uid: header
- role: interface-ingroup
  uid: /groups/api/config
type: interface
