SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
copyrights:
- Copyright (C) 2021 embedded brains GmbH (http://www.embedded-brains.de)
enabled-by: true
identifier: RTEMSDeviceDrivers
links:
- role: requirement-refinement
  uid: root
non-functional-type: design-group
rationale: null
references: []
requirement-type: non-functional
text: |
  The software product shall have software architecture components containing
  the device drivers.
type: requirement
