SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
copyrights:
- Copyright (C) 2023 embedded brains GmbH & Co. KG
enabled-by: true
links:
- role: requirement-refinement
  uid: perf-runtime-environment
name: Load
non-functional-type: performance-runtime-environment
rationale: |
  This runtime measurement environment is intended to get close to worst case
  execution conditions.
references: []
requirement-type: non-functional
text: |
  A ${/glossary/target:/term} state in which the caches are fully loaded with
  dirty data and instructions unrelated to the measured code section and data
  bus load from background tasks shall be a runtime measurement environment.
type: requirement
