SPDX-License-Identifier: CC-BY-SA-4.0 OR BSD-2-Clause
copyrights:
- Copyright (C) 2023 embedded brains GmbH & Co. KG
enabled-by: true
links:
- role: requirement-refinement
  uid: perf-runtime-environment
name: HotCache
non-functional-type: performance-runtime-environment
rationale: |
  This runtime measurement environment is used to measure the runtime of code
  sections while data and instructions of the code section are already in the
  cache.  This should give a good estimate of best case conditions.
references: []
requirement-type: non-functional
text: |
  A ${/glossary/target:/term} state in which the caches are fully loaded with
  data and instructions related to the measured code section shall be a runtime
  measurement environment.
type: requirement
